# Generated by Django 5.1.4 on 2024-12-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0002_categoria_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categories',
            field=models.ManyToManyField(to='exercicio.categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(max_length=255, verbose_name='Nome da categoria'),
        ),
    ]
