# Generated by Django 5.1.4 on 2024-12-12 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0003_produto_categories_alter_categoria_nome_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='fornecer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercicio.produto'),
            preserve_default=False,
        ),
    ]
